### ISSUE TITLE
obfuscate with chinese bug

### ISSUE THREAD

**Issue by shenqihui** [rapid7/jsobfu#12]
just like this

a.js
```
alert('你好');
```

and i act like this:

` cat a.js | jsobfu 1`

and it usually case some bug。

like the pic:

![image](https://cloud.githubusercontent.com/assets/4081063/10420897/08037070-70d0-11e5-86db-0e1d5518b720.png)

and this bug will case probability.

**Comment by shenqihui** [comment]
now i dont know how to due with this bug.

i just know how to avoid this bug.

just change `'你好‘` into `'\u4f60\u597d'` ， and this will not case this problem.

**Comment by joevennix** [comment]
Hrm, seems like a bug in how we decode unicode chars in strings. Thanks for reporting @shenqihui, I will take a closer look this weekend

**Comment by joevennix** [comment]
@shenqihui, the bug will be fixed once PR #13 lands. Thanks again for the detailed report!

**Comment by shenqihui** [comment]
@joevennix  :+1:

**Comment by wchen-r7** [comment]
Resolved in #13
