### ISSUE TITLE
spec.date is always 2014-04-09 in jsobfu.gemspec

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/jsobfu#17]
I'm not familiar with this, but it doesn't make a lot of sense this date is always the same in Rubygems:
https://rubygems.org/gems/jsobfu

<img width="229" alt="screen shot 2015-10-30 at 1 45 37 pm" src="https://cloud.githubusercontent.com/assets/1170914/10854882/8acad0ee-7f0c-11e5-8d9e-1f7601ee18eb.png">

Egypt told me Rubygems should know the correct published date without spec.date, so maybe we should just remove it?

**Comment by joevennix** [comment]
Weird. Yeah we should remove it.

**Comment by busterb** [comment]
The date is now gone from the gemspec
