### ISSUE TITLE
JSObfu should have more constructor options

### ISSUE THREAD

**Issue by joevennix** [rapid7/jsobfu#8]
As per https://github.com/rapid7/metasploit-framework/issues/4728:

It would be useful to expose the following options in the JSObfu constructor:
- `rewrite_globals [boolean]`, in case you want to leave global vars alone
- `obfuscate_strings [boolean]`, in case you don't want to obfuscate strings (this eats memory and can make heap sprays unreliable)
- `strip_whitespace [boolean]`, in case you don't want to remove unnecessary whitespace.
- `rename_vars [boolean]`, in case you don't want to rename vars.

**Comment by jvazquez-r7** [comment]
See also https://github.com/rapid7/metasploit-framework/pull/4726#discussion-diff-24275566R144 for some discussion about this topic!

**Comment by joevennix** [comment]
I took a different approach and just added a `memory_sensitive` option. The PR is here https://github.com/rapid7/jsobfu/pull/9
